# Generated by Django 4.2.1 on 2023-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('draft', 'Чернетка')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва Категорії'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва тегу'),
        ),
    ]
