# Generated by Django 4.2.1 on 2023-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_article_status_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
